AllCops:
  TargetRubyVersion: 2.0
  DisplayCopNames: true

LineLength:
  Max: 130
  Severity: warning

Style/OneLineConditional:
  Enabled: true

Style/StringLiterals:
  # Being consistent with Puppet
  EnforcedStyle: single_quotes

# Since we're using Ruby >= 2.0 we can use the new hash syntax
Style/HashSyntax:
  Enabled: true

# We are setting absurdly high limits but should work to tighten these up.
Metrics/AbcSize:
  Max: 100
  Severity: warning

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Max: 500
  Severity: warning

Metrics/CyclomaticComplexity:
  Max: 50
  Severity: warning

Metrics/MethodLength:
  Max: 100
  Severity: warning

Metrics/PerceivedComplexity:
  Max: 50
  Severity: warning

# Indentation
CaseIndentation:
  IndentOneStep: false

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

# To let us use a '-' in the gem name
Style/FileName:
  Enabled: false

# Sometimes it's cleaner without this
Style/Documentation:
  Enabled: false

# To fix later
Style/PercentLiteralDelimiters:
  Enabled: false
Style/VariableNumber:
  Enabled: false
Security/YAMLLoad:
  Enabled: false
Lint/AmbiguousBlockAssociation:
  Enabled: false
Lint/UnifiedInteger:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/IndentHeredoc:
  Enabled: false
Style/ExtraSpacing:
  Enabled: false
