AllCops:
  TargetRubyVersion: 3.1
  DisplayCopNames: true
  NewCops: enable
  SuggestExtensions: false

Style/OneLineConditional:
  Enabled: true

Style/StringLiterals:
  # Being consistent with Puppet
  EnforcedStyle: single_quotes

# We are setting absurdly high limits but should work to tighten these up.
Metrics/AbcSize:
  Max: 100
  Severity: warning

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Max: 500
  Severity: warning

Metrics/CyclomaticComplexity:
  Max: 50
  Severity: warning

Metrics/MethodLength:
  Max: 100
  Severity: warning

Metrics/PerceivedComplexity:
  Max: 50
  Severity: warning

# To let us use a '-' in the gem name
Naming/FileName:
  Enabled: false
Naming/VariableNumber:
  Enabled: false

# Indentation
Layout/CaseIndentation:
  IndentOneStep: false
Layout/EndAlignment:
  EnforcedStyleAlignWith: variable
Layout/LineLength:
  Max: 130
  Severity: warning

# Sometimes it's cleaner without this
Style/Documentation:
  Enabled: false

# To fix later
Style/FormatStringToken:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Security/YAMLLoad:
  Enabled: false
Lint/AmbiguousBlockAssociation:
  Enabled: false
Lint/UnifiedInteger:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/YodaCondition:
  Enabled: false
Layout/HeredocIndentation:
  Enabled: false
Layout/ExtraSpacing:
  Enabled: false
Style/WordArray:
  Enabled: false
