#!/usr/bin/env bash

echo 'Starting script/bootstrap'

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )"

rm -rf "${DIR}/.bundle"
rm -f "${DIR}/.puppet_version"
set -e
shopt -s extglob
cd "${DIR}/bin" && rm -f !(octocatalog-diff)
set +e

echo 'Running bundler'
# get ruby version in format '2.1.0' from example 2.1.0p000
RVERSION=$(ruby -v | awk '{ print $2 }' | sed 's/p.*//')
# write RVERSION to .ruby_version file
echo $RVERSION > "${DIR}/.ruby_version"

echo "Ruby version is $RVERSION"
cd "${DIR}" && \
  rm -f Gemfile.lock && \
  bundle install --without='' --no-prune --path vendor/bundle --local && \
  bundle binstubs puppet rake rspec-core rubocop parallel_tests && \
  chmod 0755 bin/octocatalog-diff
if [ $? -ne 0 ]; then
  echo 'bundle install failed - aborting bootstrap'
  exit 1
fi

# Symlink the git pre-commit script to the right place
mkdir "${DIR}/.git/hooks" 2>/dev/null
ln -fs "${DIR}/script/git-pre-commit" "${DIR}/.git/hooks/pre-commit"

# Create the .puppet_version file for use during CI
# This value is consumed by script/puppet.
if [ -f "${DIR}/Gemfile.lock" ]; then
  grep ' puppet ' "${DIR}/Gemfile.lock" | head -1 | awk '{ print $2 }' | tr -d "()" > "${DIR}/.puppet_version"
else
  echo "Expected file ${DIR}/Gemfile.lock is missing!"
  exit 1
fi

echo 'Completed script/bootstrap successfully'
exit 0
