#!/bin/bash

# Wrap "bundle" as it's used in the CI build scripts.
set -e
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )"
cd "$DIR"
DESIRED_BUNDLER_VERSION=$(grep "add_development_dependency 'bundler'" octocatalog-diff.gemspec  | cut -d"'" -f4)
bundle "_${DESIRED_BUNDLER_VERSION}_" "$@"
