#!/bin/bash

# Script runs before travis CI builds.

echo "travis_fold:start:travis-before-install"
set -ex
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )"

cd "$DIR"
DESIRED_BUNDLER_VERSION=$(grep "add_development_dependency 'bundler'" octocatalog-diff.gemspec  | cut -d"'" -f4)
gem install bundler -v "$DESIRED_BUNDLER_VERSION"

BUNDLER_VERSIONS=$(gem list bundler | grep ^bundler | cut -d'(' -f2 | cut -d')' -f1 | tr "," " " | grep -v "default")
for v in $BUNDLER_VERSIONS; do
  if [ "$v" != "$DESIRED_BUNDLER_VERSION" ]; then
    gem uninstall bundler --force -v "$v" || true
  fi
done
echo "travis_fold:end:travis-before-install"
