---
name: Assign Dependabot PR to Compute Foundation Project

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, labeled]

permissions:
  contents: read
  pull-requests: write

jobs:
  add-to-project:
    name: Add to Compute Foundation Project Board
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.0
        with:
          project-url: https://github.com/orgs/github/projects/5753/ # Compute Foundation Project Board
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: dependencies,external-dependency
